export { default as FcSectionCard } from './FcSectionCard.vue'
export { default as FcEmpty } from './FcEmpty.vue'
export { default as FcSkeleton } from './FcSkeleton.vue'
export { default as FcTag } from './FcTag.vue'
export { default as FcTagGroup } from './FcTagGroup.vue'
export { default as FcAvatar } from './FcAvatar.vue'
export { default as FcImage } from './FcImage.vue'
export { default as FcIcon } from './FcIcon.vue'

export type { FcSectionCardProps } from './FcSectionCard.vue'
export type { FcEmptyProps } from './FcEmpty.vue'
export type { FcSkeletonProps } from './FcSkeleton.vue'
export type { FcTagProps } from './FcTag.vue'
export type { FcTagGroupProps } from './FcTagGroup.vue'
export type { FcAvatarProps } from './FcAvatar.vue'
export type { FcImageProps } from './FcImage.vue'
export type { FcIconProps } from './FcIcon.vue'
